# Generated by Django 5.2.4 on 2025-08-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_errorlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='error_type',
        ),
    ]
